name: Build and Push Docker Images

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      image:
        description: 'Which image to build'
        required: true
        default: 'all'
        type: choice
        options:
        - all
        - llvm-python
        - rtl-sim

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: github.actor == github.repository_owner # Only run for the repository owner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build llvm-python image
        if: github.event.inputs.image == 'all' || github.event.inputs.image == 'llvm-python'
        run: make llvm-python

      - name: Build rtl-sim image
        if: github.event.inputs.image == 'all' || github.event.inputs.image == 'rtl-sim'
        run: make rtl-sim

      - name: Push images
        run: make push
